#
# Elasticsearch Dockerfile
#
# Started with:
#    https://github.com/dockerfile/elasticsearch
# But hasn't been updated in 2 years and makes bad Java references
#
FROM ubuntu:14.04

USER root
ENV TERM xterm

RUN apt-get -y -q update
RUN apt-get -y -q upgrade
RUN apt-get -y -q install software-properties-common htop
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get -y -q update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get -y -q install oracle-java8-installer
RUN update-java-alternatives -s java-8-oracle
RUN  apt-get -y -q install libcurl3 curl
RUN apt-get -y -q install jq

RUN groupadd -g 1000 elasticsearch && useradd -m -u 1000 -g 0 -p 'papAq5PwY/QQM' -s /bin/bash elasticsearch

ENV ES_PKG_NAME elasticsearch-2.3.5

# Install Elasticsearch.
RUN \
  cd / && \
  wget https://download.elasticsearch.org/elasticsearch/elasticsearch/$ES_PKG_NAME.tar.gz && \
  tar xvzf $ES_PKG_NAME.tar.gz && \
  rm -f $ES_PKG_NAME.tar.gz && \
  mv /$ES_PKG_NAME /elasticsearch

# Use the -v /data/es:/data/es flags to override the parts we want to externalize
# Define mountable directories.
VOLUME ["/data/es"]

# Mount elasticsearch.yml config
ADD elasticsearch.yml /elasticsearch/config/elasticsearch.yml

RUN mkdir /usr/share/elasticsearch
RUN mkdir /usr/share/elasticsearch/plugins

# Make sure ES running as 'elasticsearch' can access the needed directories
RUN chown elasticsearch /data/es
RUN if [ ! -d "/usr/share/elasticsearch" ] ; then mkdir /usr/share/elasticsearch ; chown elasticsearch /usr/share/elasticsearch ; fi ; 
RUN if [ ! -d "/usr/share/elasticsearch/plugins" ] ; then mkdir /usr/share/elasticsearch/plugins ; chown elasticsearch /usr/share/elasticsearch/plugins ; fi ; 

# Define working directory.
WORKDIR /elasticsearch

# Make head available at localhost:9200/_plugin/head ... (plugin install only works if elasticsearch is running)
#Define install Head script ... yes we must start and stop ES twice.
RUN echo '#!/bin/bash\n\
export ES_HOME=/elasticsearch\n\
/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -p /tmp/elasticsearch.pid &\n\
while [ ! "`curl -s -XGET 127.0.0.1:9200 | jq \".tagline == \\\"You Know, for Search\\\""`" == "true" ]; do echo "waiting for ES"; sleep 1; done\n\
/elasticsearch/bin/plugin install mobz/elasticsearch-head\n\
kill -9 `cat /tmp/elasticsearch.pid`\n\
/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -p /tmp/elasticsearch.pid &\n\
while [ ! "`curl -s -XGET 127.0.0.1:9200 | jq \".tagline == \\\"You Know, for Search\\\""`" == "true" ]; do echo "waiting for ES"; sleep 1; done\n\
kill -9 `cat /tmp/elasticsearch.pid`\n\
' > /usr/bin/elasticsearch_install_head.sh && chmod a+rwx /usr/bin/elasticsearch_install_head.sh
# Install Head
RUN /bin/bash -C /usr/bin/elasticsearch_install_head.sh

# Define default command.
RUN echo '#!/bin/bash\n\
export ES_HOME=/elasticsearch\n\
/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true -p /tmp/elasticsearch.pid\n\
' >> /usr/bin/elasticsearch_start.sh && chmod a+rwx /usr/bin/elasticsearch_start.sh
CMD /bin/bash -C /usr/bin/elasticsearch_start.sh


# Expose ports.
#   - 9200: HTTP
#   - 9300: transport
EXPOSE 9200
EXPOSE 9300
