#!/usr/bin/env bash

set -o errexit

compose_file=deploy/compose/dev.yml
helpme=$"Usage: $0 {up|tail|(Compose COMMAND)} [Compose options]"

case "$1" in
  -h|--help)
    docker-compose $1
    echo $helpme
    ;;

  up)
    git pull
    docker-compose -f $compose_file up -d
    docker-compose -f $compose_file scale image-fetcher=4

    if [ "$2" == "deploy" ]; then
      deploy/compose/slc-deploy.dev.sh
    fi
    ;;

  tail)
    docker-compose -f $compose_file logs --tail 100 -f $2
    ;;

  log*)
    docker-compose -f $compose_file logs $2
    ;;

  ps|down|stop|restart|exec|scale|rm|config|version)
    docker-compose -f $compose_file "$@"
    ;;

  *)
    echo $helpme
    exit 1

esac
