#!/usr/bin/env bash

# set -o errexit

# get additional files from env var
compose_files=$"-f deploy/compose/services.yml `printenv COMPOSE_FILES`"
helpme=$"Usage: $0 {up|tail|(Compose COMMAND)} [Compose options]"

case "$1" in
  -h|--help)
    docker-compose $1
    echo $helpme
    ;;

  up)
    git pull
    docker-compose $compose_files up -d

    if [ "$2" == "deploy" ]; then
      script/deploy/slc-deploy.js
    fi
    ;;

  tail)
    docker-compose $compose_files logs --tail 100 -f $2
    ;;

  log*)
    docker-compose $compose_files logs $2
    ;;

  ps|down|stop|restart|exec|scale|rm|config|version)
    docker-compose $compose_files "$@"
    ;;

  *)
    echo $helpme
    exit 1

esac
